### ISSUE TITLE
Observed an issue where redis-server hangs indefinitely and becomes unresponsive after call to TSDB_madd()

### ISSUE THREAD

**Issue by jgauth** [RedisTimeSeries/RedisTimeSeries#1183]
```
Redis server v=6.2.6
malloc=jemalloc-5.1.0
RedisTimeSeries (v1.4.12-1-g8fab5dd)
```
redis conf:
```
io-threads 4
io-threads-do-reads yes
```
Observed a failure while running redis-server with RedisTimeSeries in which the redis-server became completely unresponsive. The process was sitting at ~100% cpu in `top` and calling `redis-cli` would hang indefinitely. Obtained the following traces on the hung process:

`strace` was hanging on a futex call
```
strace: Process 6978 attached with 11 threads
[pid 10991] futex(0x7f49c020747c, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  6984] futex(0x563011b6df38, FUTEX_WAIT_PRIVATE, 2, NULLstrace: [ Process PID=6978 runs in x32 mode. ]
 <unfinished ...>
[pid 10993] futex(0x7f49c0207608, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 10992] futex(0x7f49c0207544, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  6983] futex(0x563011b6df10, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid  6981] futex(0x563011b52d28, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  6980] futex(0x563011b52cf8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  6979] futex(0x563011b52cc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  6985] futex(0x7f49c02073b4, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  6982] futex(0x563011b6dee8, FUTEX_WAIT_PRIVATE, 2, NULL
```
`ltrace` showed the process spin-looping on memset / memmove calls
```
[pid 6978] memset(0x7f49ad06f7f8, '\0', 56)     = 0x7f49ad06f7f8
[pid 6978] memmove(0x7f498c1a863e, "f", 1)     = 0x7f498c1a863e
[pid 6978] memmove(0x7f498c1a863f, "\363", 1)     = 0x7f498c1a863f
[pid 6978] memset(0x7f49ad06f7f8, '\0', 56)     = 0x7f49ad06f7f8
[pid 6978] memmove(0x7f498c1a863e, "q", 1)     = 0x7f498c1a863e
[pid 6978] memmove(0x7f498c1a863f, "\345", 1)     = 0x7f498c1a863f
[pid 6978] memset(0x7f49ad06f7f8, '\0', 56)     = 0x7f49ad06f7f8
[pid 6978] memmove(0x7f498c1a863e, "}", 1)     = 0x7f498c1a863e
[pid 6978] memmove(0x7f498c1a863f, "\362", 1)     = 0x7f498c1a863f
```
`gdb` shows a backtrace originating from a TSDB_madd() call
```
(gdb) bt
#0  0x00007f49bf9eee30 in Compressed_ReadNext () from target:/etc/redis/redistimeseries.so
#1  0x00007f49bf9f5d71 in SeriesIteratorGetNext () from target:/etc/redis/redistimeseries.so
#2  0x00007f49bf9f6597 in SeriesCalcRange () from target:/etc/redis/redistimeseries.so
#3  0x00007f49bf9f69e7 in SeriesUpsertSample () from target:/etc/redis/redistimeseries.so
#4  0x00007f49bf9f03aa in internalAdd () from target:/etc/redis/redistimeseries.so
#5  0x00007f49bf9f1e71 in TSDB_madd () from target:/etc/redis/redistimeseries.so
#6  0x000056301181eba6 in RedisModuleCommandDispatcher (c=0x7f4997dde140) at module.c:694
#7  0x000056301179298c in call (c=0x7f4997dde140, flags=15) at server.c:3721
#8  0x000056301179459e in processCommand (c=c@entry=0x7f4997dde140) at server.c:4241
#9  0x00005630117a806c in processCommandAndResetClient (c=c@entry=0x7f4997dde140) at networking.c:2039
#10 0x00005630117aa9ba in processInputBuffer (c=0x7f4997dde140) at networking.c:2140
#11 0x0000563011840a4a in callHandler (handler=<optimized out>, conn=0x7f49a1cf8140) at connhelpers.h:79
#12 connSocketEventHandler (el=<optimized out>, fd=<optimized out>, clientData=0x7f49a1cf8140, mask=<optimized out>) at connection.c:295
#13 0x000056301178b0f7 in aeProcessEvents (eventLoop=eventLoop@entry=0x7f49c00230a0, flags=flags@entry=27) at ae.c:427
#14 0x000056301178b4ed in aeMain (eventLoop=0x7f49c00230a0) at ae.c:487
#15 0x00005630117878fa in main (argc=<optimized out>, argv=<optimized out>) at server.c:6401
(gdb) frame 0
#0  0x00007f49bf9eee30 in Compressed_ReadNext () from target:/etc/redis/redistimeseries.so
(gdb) info thread
Id   Target Id         Frame
* 1    Thread 0x7f49c1567f80 (LWP 6978) "redis-server" 0x00007f49bf9eee30 in Compressed_ReadNext () from target:/etc/redis/redistimeseries.so
     Thread 0x7f49bf9e1700 (LWP 6979) "bio_close_file" 0x00007f49c098cad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x563011b52cc8 <bio_newjob_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
     Thread 0x7f49bf1e0700 (LWP 6980) "bio_aof_fsync" 0x00007f49c098cad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x563011b52cf8 <bio_newjob_cond+88>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
     Thread 0x7f49be9df700 (LWP 6981) "bio_lazy_free" 0x00007f49c098cad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x563011b52d28 <bio_newjob_cond+136>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
     Thread 0x7f49be1de700 (LWP 6982) "io_thd_1" __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
     Thread 0x7f49bd9dd700 (LWP 6983) "io_thd_2" __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
     Thread 0x7f49bd1dc700 (LWP 6984) "io_thd_3" __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
     Thread 0x7f49bc9db700 (LWP 6985) "jemalloc_bg_thd" 0x00007f49c098cad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f49c02073b4) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
     Thread 0x7f49b9fff700 (LWP 10991) "jemalloc_bg_thd" 0x00007f49c098cad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f49c020747c) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
     Thread 0x7f49b93ff700 (LWP 10992) "jemalloc_bg_thd" 0x00007f49c098cad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f49c0207544) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
11   Thread 0x7f49b3fff700 (LWP 10993) "jemalloc_bg_thd" 0x00007f49c098cad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f49c0207608) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
(gdb) 
```
The only way we were able to resolve the issue was restarting the redis-server process. 

I am currently working on attempting to reproduce the issue, but haven't been able to so far. Our current best guess for the cause is some unsafe thread operation initiated from RedisTimeSeries. Looking at the Redis release notes, we saw that [6.2.7](https://github.com/redis/redis/releases/tag/6.2.7) fixes an issue where `RM_ReplyWithError` calls could violate thread safety. 

Opening an issue to see if you think it's likely the issue we saw was caused by an unsafe `RM_ReplyWithError` call, and therefore would be fixed by upgrading to Redis 6.2.7. Alternatively, if you have any other ideas for what could have caused the issue or ways we can reproduce it, we would love to help track down it down and fix it.

**Comment by OfirMos** [comment]
Hi, is it possible for you to upgrade to 1.6 to check if you have the issue also on 1.6?

**Comment by OfirMos** [comment]
Hi [jgauth](https://github.com/jgauth), some questions:
1. What is the madd command your are using (specially how many sample you are trying to add)?
2. Can you also send the output of "info all"?
Thanks!

**Comment by jgauth** [comment]
Hi @OfirMos , thanks for the response. Our attempts to  reproduce have been unsuccessful.

> code in the stack-trace was completely rewritten in master, is it ok by you to upgrade to master latest

Which part of the code are you referring to that was rewritten - Redis or RedisTimeSeries?

**Comment by OfirMos** [comment]
Hi @jgauth,
I'm talking about RedisTimeSeries, so the upgrade shouldn't affect this part of the code we see in the stack trace.
