### ISSUE TITLE
Compile on RedHat

### ISSUE THREAD

**Issue by pasalino** [RedisTimeSeries/RedisTimeSeries#212]
When i compile on RedHat i have this exceptions:

Traceback (most recent call last):
  File "../deps/readies/bin/platform", line 20, in <module>
    platform = Platform()
  File "/home/sumame/RedisTimeSeries/deps/readies/paella/platform.py", line 25, in __init__
    Assert(False), "Cannot determine distribution"
NameError: name 'Assert' is not defined
Traceback (most recent call last):
  File "../deps/readies/bin/platform", line 20, in <module>
    platform = Platform()
  File "/home/sumame/RedisTimeSeries/deps/readies/paella/platform.py", line 25, in __init__
    Assert(False), "Cannot determine distribution"
NameError: name 'Assert' is not defined
Traceback (most recent call last):
  File "../deps/readies/bin/platform", line 20, in <module>
    platform = Platform()
  File "/home/sumame/RedisTimeSeries/deps/readies/paella/platform.py", line 25, in __init__
    Assert(False), "Cannot determine distribution"
NameError: name 'Assert' is not defined
Building rmutil...
Traceback (most recent call last):
  File "../../deps/readies/bin/platform", line 20, in <module>
    platform = Platform()
  File "/home/sumame/RedisTimeSeries/deps/readies/paella/platform.py", line 25, in __init__
    Assert(False), "Cannot determine distribution"
NameError: name 'Assert' is not defined
Traceback (most recent call last):
  File "../../deps/readies/bin/platform", line 20, in <module>
    platform = Platform()
  File "/home/sumame/RedisTimeSeries/deps/readies/paella/platform.py", line 25, in __init__
    Assert(False), "Cannot determine distribution"
NameError: name 'Assert' is not defined
Traceback (most recent call last):
  File "../../deps/readies/bin/platform", line 20, in <module>
    platform = Platform()
  File "/home/sumame/RedisTimeSeries/deps/readies/paella/platform.py", line 25, in __init__
    Assert(False), "Cannot determine distribution"
NameError: name 'Assert' is not defined
make[1]: Nothing to be done for `all'.
Linking ../bin/--release/redistimeseries.so...
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
../bin/--release/src/tsdb.o: In function `SeriesAddSample':
tsdb.c:(.text+0x469): undefined reference to `intrev64'
../bin/--release/src/tsdb.o: In function `SeriesQuery':
tsdb.c:(.text+0x506): undefined reference to `intrev64'
collect2: error: ld returned 1 exit status
make: *** [../bin/--release/redistimeseries.so] Error 1

**Comment by rafie** [comment]
Which RedHat version? (cat /etc/os-release and lsb_release -a can help).

**Comment by pasalino** [comment]
In this moment i had to remove the line containing Assert in platform.py and now compile.

The Version is :

NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"


LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.5 (Maipo)
Release:	7.5
Codename:	Maipo
