### ISSUE TITLE
urlib2 issue in make all

### ISSUE THREAD

**Issue by edwarts** [RedisTimeSeries/RedisTimeSeries#221]
When I try to build from src, I got this issue, please have a look at the error below:
Traceback (most recent call last):
  File "../../deps/readies/bin/platform", line 9, in <module>
    import paella
  File "/home/xxx/RedisTimeSeries/deps/readies/paella/__init__.py", line 4, in <module>
    from .files import *
  File "/home/xxx/RedisTimeSeries/deps/readies/paella/files.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
Traceback (most recent call last):
  File "../../deps/readies/bin/platform", line 9, in <module>
    import paella
  File "/home/xxx/RedisTimeSeries/deps/readies/paella/__init__.py", line 4, in <module>
    from .files import *
  File "/home/xxx/RedisTimeSeries/deps/readies/paella/files.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
Traceback (most recent call last):
  File "../../deps/readies/bin/platform", line 9, in <module>
    import paella
  File "/home/xxx/RedisTimeSeries/deps/readies/paella/__init__.py", line 4, in <module>
    from .files import *
  File "/home/xxx/RedisTimeSeries/deps/readies/paella/files.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
I am using python 3.6.9 and not sure where I should do the make all, I am following the steps in the readme. It only got the error when I run make all. How I should install the urlib2?

**Comment by rafie** [comment]
No need to install urllib2 (although it can prevent the error).
RedisTimeSeries uses Python2 for its build environment automation, so running 'make setup' will put everything in order. Do note that this will install various packages on your system, so you are advised to review system-setup.py in advance for possible consequences.
PR #222 fixes the automation infrastructure for Python2/3 usage of urllib.
It also updates documentation regarding up-to-date build requirements installation.

**Comment by edwarts** [comment]
Many thanks! It is really helpful and works!
