### ISSUE TITLE
assertion fails at "tsdb.c", line=629: minTimestamp <= funcs->GetLastTimestamp(chunk)

### ISSUE THREAD

**Issue by filipecosta90** [RedisTimeSeries/RedisTimeSeries#499]
Checking the [redistimeseries-py failure](https://app.circleci.com/pipelines/github/RedisTimeSeries/redistimeseries-py/324/workflows/0fb0b959-9b98-46be-b5ea-696ee07d8aa9/jobs/651) it's truly a failure on our main repo.
running the redistimeseries-py tests:
```
redistimeseries-py$ python test_commands.py
```

produces the following failed assert on `getFirstValidTimestamp`, more specifically at:
```
// should never fail since we just trimmed
    assert(minTimestamp <= funcs->GetLastTimestamp(chunk));
```
here is the bt:
```
hread 1 "redis-server" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6028e8e859 in __GI_abort () at abort.c:79
#2  0x00007f6028e8e729 in __assert_fail_base (fmt=0x7f6029024588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f6028e5e2a8 "minTimestamp <= funcs->GetLastTimestamp(chunk)", 
    file=0x7f6028e5e2a1 "tsdb.c", line=629, function=<optimized out>) at assert.c:92
#3  0x00007f6028e9ff36 in __GI___assert_fail (assertion=0x7f6028e5e2a8 "minTimestamp <= funcs->GetLastTimestamp(chunk)", file=0x7f6028e5e2a1 "tsdb.c", line=629, 
    function=0x7f6028e5e2e0 <__PRETTY_FUNCTION__.5343> "getFirstValidTimestamp") at assert.c:101
#4  0x00007f6028e5159d in getFirstValidTimestamp (series=0x564fbc47a8f0, skipped=0x7ffead8af600) at tsdb.c:629
#5  0x00007f6028e47f8e in TSDB_info (ctx=0x7ffead8af640, argv=0x7f6028b2e210, argc=2) at module.c:282
#6  0x0000564fbaf4056d in RedisModuleCommandDispatcher (c=0x7f6028b1cd80) at module.c:642
#7  0x0000564fbaec5441 in call (c=0x7f6028b1cd80, flags=15) at server.c:3277
#8  0x0000564fbaec5fee in processCommand (c=c@entry=0x7f6028b1cd80) at server.c:3691
#9  0x0000564fbaed4634 in processCommandAndResetClient (c=c@entry=0x7f6028b1cd80) at networking.c:1809
#10 0x0000564fbaed8fef in processInputBuffer (c=0x7f6028b1cd80) at networking.c:1891
#11 0x0000564fbaf5dc9c in callHandler (handler=<optimized out>, conn=0x7f6028a150c0) at connhelpers.h:79
#12 connSocketEventHandler (el=<optimized out>, fd=<optimized out>, clientData=0x7f6028a150c0, mask=<optimized out>) at connection.c:285
#13 0x0000564fbaebe6d3 in aeProcessEvents (eventLoop=eventLoop@entry=0x7f6028a0b540, flags=flags@entry=27) at ae.c:479
#14 0x0000564fbaebea0d in aeMain (eventLoop=0x7f6028a0b540) at ae.c:539
#15 0x0000564fbaebaf25 in main (argc=<optimized out>, argv=0x7ffead8afa08) at server.c:5234
```

**Comment by gkorland** [comment]
Is it the same issue https://github.com/RedisTimeSeries/RedisTimeSeries/pull/497?

**Comment by filipecosta90** [comment]
> Is it the same issue #497?

Yes. Totally right. linking the issue
