### ISSUE TITLE
keyspace tests fail

### ISSUE THREAD

**Issue by lukepalmer** [RedisTimeSeries/RedisTimeSeries#838]
I get the below when running 'make test'. Very happy to collect any more information you like.

test_ts_keyspace:test_keyspace
	[ERROR]
	Unhandled exception: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/tmp/tmp.m0uqRiocqi/venv/lib64/python3.6/site-packages/RLTest/__main__.py", line 543, in _runTest
    fn()
  File "/tmp/tmp.m0uqRiocqi/RedisTimeSeries/tests/flow/test_ts_keyspace.py", line 28, in test_keyspace
    assert_msg(env, pubsub.get_message(timeout=1), 'pmessage', b'ts.add')
  File "/tmp/tmp.m0uqRiocqi/RedisTimeSeries/tests/flow/test_ts_keyspace.py", line 7, in assert_msg
    env.assertEqual(expected_type, msg['type'])
TypeError: 'NoneType' object is not subscriptable
test_ts_keyspace:test_keyspace_create_rules
	[ERROR]
	Unhandled exception: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/tmp/tmp.m0uqRiocqi/venv/lib64/python3.6/site-packages/RLTest/__main__.py", line 543, in _runTest
    fn()
  File "/tmp/tmp.m0uqRiocqi/RedisTimeSeries/tests/flow/test_ts_keyspace.py", line 72, in test_keyspace_create_rules
    assert_msg(env, pubsub.get_message(timeout=1), 'pmessage', b'ts.create')
  File "/tmp/tmp.m0uqRiocqi/RedisTimeSeries/tests/flow/test_ts_keyspace.py", line 7, in assert_msg
    env.assertEqual(expected_type, msg['type'])
TypeError: 'NoneType' object is not subscriptable
test_ts_keyspace:test_keyspace_rules_send
	[ERROR]
	Unhandled exception: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/tmp/tmp.m0uqRiocqi/venv/lib64/python3.6/site-packages/RLTest/__main__.py", line 543, in _runTest
    fn()
  File "/tmp/tmp.m0uqRiocqi/RedisTimeSeries/tests/flow/test_ts_keyspace.py", line 109, in test_keyspace_rules_send
    assert_msg(env, pubsub.get_message(timeout=1), 'pmessage', b'ts.create')
  File "/tmp/tmp.m0uqRiocqi/RedisTimeSeries/tests/flow/test_ts_keyspace.py", line 7, in assert_msg
    env.assertEqual(expected_type, msg['type'])
TypeError: 'NoneType' object is not subscriptable

**Comment by danni-m** [comment]
@lukepalmer thanks for the report, can you provide more details?
1. which git revision are you using?
2. how did you run the tests?

**Comment by lukepalmer** [comment]
Ah: tests fail against Redis 6.0.10 (what I happened to have) but pass with 6.2.5. So I will just use the current version.  Thank you for looking all the same.

Side note: is v1.6.0 current stable? I don't see a release for it so wasn't sure.

**Comment by lukepalmer** [comment]
Thanks very much.

Please ping me if it'd be helpful for me to contribute a test that an expected redis-server version is present. Otherwise, all good here.
