### ISSUE TITLE
make setup fails on Raspberry Pi Buster

### ISSUE THREAD

**Issue by baileyji** [RedisTimeSeries/RedisTimeSeries#842]
> ➜  RedisTimeSeries git:(master) make setup                      
> Setting up system...
> Traceback (most recent call last):
>   File "./system-setup.py", line 56, in <module>
>     RedisTimeSeriesSetup(nop = args.nop).setup()
>   File "./system-setup.py", line 16, in __init__
>     paella.Setup.__init__(self, nop)
>   File "/home/pi/src/RedisTimeSeries/deps/readies/paella/setup.py", line 337, in __init__
>     self.package_manager = PackageManager.detect(self.platform, self.runner)
>   File "/home/pi/src/RedisTimeSeries/deps/readies/paella/setup.py", line 113, in detect
>     raise self.Error("Cannot determine package manager for distibution %s" % platform.dist)
> NameError: name 'self' is not defined
> make: *** [Makefile:25: setup] Error 1

**Comment by chayim** [comment]
Hi @baileyji thanks for reporting this. Here's what I've tried to do to reproduce the issue. I've pulled [**docker:buster (arm)**](https://hub.docker.com/layers/debian/library/debian/buster/images/sha256-340092a9d7ecb6b99fa8bb16734f7120b520082f04f94c86222b2a22c3ff4afd?context=explore)  and run the following inside of that docker instance.  Can you please let me know how what I have differs from you? I checked out hash [fda35e0b0c27c1b7c3f0b71127932d7a25c4f06d](https://github.com/RedisTimeSeries/RedisTimeSeries/commit/fda35e0b0c27c1b7c3f0b71127932d7a25c4f06d)

**cat /etc/issue**
```
Debian GNU/Linux 10 \n \l 
```

**cat /etc/debian_version**
```
10.10
```


**uname -a**
```
Linux 9aed9e488d15 5.4.0-1045-aws #47~18.04.1-Ubuntu SMP Tue Apr 13 16:00:48 UTC 2021 aarch64 GNU/Linux
```

```
apt-get update
apt-get upgrade -y
apt-get install -y make git
git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries 
```

**make setup**

```
Setting up system...
apt-get -qq update -y
/usr/bin/python3  -m pip install --disable-pip-version-check wheel
/usr/bin/python3  -m pip install --disable-pip-version-check setuptools --upgrade
apt-get -qq install -y git jq curl
/build/deps/readies/bin/enable-utf8
/build/deps/readies/bin/getgcc
apt-get -qq install -y lcov
/usr/bin/python3  /build/deps/readies/bin/getrmpytools
/usr/bin/python3  -m pip install --disable-pip-version-check -r tests/flow/requirements.txt
```

**make**
```
Compiling chunk.c...
Compiling compaction.c...
Compiling compressed_chunk.c...
Compiling config.c...
Compiling generic_chunk.c...
Compiling gorilla.c...
Compiling indexer.c...
Compiling module.c...
Compiling parse_policies.c...
Compiling query_language.c...
Compiling reply.c...
Compiling rdb.c...
Compiling resultset.c...
Compiling tsdb.c...
Compiling series_iterator.c...
Compiling filter_iterator.c...
Compiling fpconv.c...
Compiling gears_integration.c...
Compiling gears_commands.c...
Building rmutil...
Building libfast_double_parser_c...
Compiling ...
Compiling ../../deps/RedisModulesSDK/rmutil/util.c...
Compiling ../../deps/RedisModulesSDK/rmutil/strings.c...
Compiling ../../deps/RedisModulesSDK/rmutil/sds.c...
Compiling ../../deps/RedisModulesSDK/rmutil/vector.c...
Compiling ../../deps/RedisModulesSDK/rmutil/alloc.c...
Compiling ../../deps/RedisModulesSDK/rmutil/periodic.c...
Creating ../../bin/linux-arm64v8-release/fast_double_parser_c/libfast_double_parser_c.a...
Creating ../../bin/linux-arm64v8-release/rmutil/librmutil.a...
Linking ../bin/linux-arm64v8-release/redistimeseries.so...
```

**Comment by baileyji** [comment]
The first thing that comes to mind is I wasn't using docker. 

uname -a
Linux cloudlight 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux

cat /etc/issue: 
Raspbian GNU/Linux 10 \n \l

cat /etc/debian_version 
10.10

I've had this issue since at least early this year. I'm on d7ccf2a41cb2fdc92d00f3cc930477467e661916 (v1.4.10) as master won't load with redis-server 5.0.3 (which is what is in apt and I'd rather not build it from source) though I did try with a fresh pull of master. If I had to guess its just a simple issue of string matching with that Raspbian string but the install script was beyond me to to be confident in what I needed to patch and not break things.

**Comment by chayim** [comment]
@baileyji I've just cloned the v1.4.10 tag [same revision](https://github.com/RedisTimeSeries/RedisTimeSeries/commit/d7ccf2a41cb2fdc92d00f3cc930477467e661916), and can't reproduce. But yes, I'm in a docker, and you're not.  What python version are you running? The various commands I linked to above (system-setup.py especially) depend on python3.  Assuming you have python2 - would you be amenable to running **deps/readies/bin/getpy3** and then re-running system-setup.py and friends?

**Comment by shan4usmani** [comment]
Hi, 
I am getting the exact same error. I am trying to run this on Raspbian Stretch with Python3. I have cloned the repository and when I run "make setup", it gives the exact same error: 

Setting up system...
Traceback (most recent call last):
File "./system-setup.py", line 56, in
RedisTimeSeriesSetup(nop = args.nop).setup()
File "./system-setup.py", line 16, in init
paella.Setup.init(self, nop)
File "/home/pi/src/RedisTimeSeries/deps/readies/paella/setup.py", line 337, in init
self.package_manager = PackageManager.detect(self.platform, self.runner)
File "/home/pi/src/RedisTimeSeries/deps/readies/paella/setup.py", line 113, in detect
raise self.Error("Cannot determine package manager for distibution %s" % platform.dist)
NameError: name 'self' is not defined
make: *** [Makefile:25: setup] Error 1

when running the make setup commands individually, the error appears on the following line: 

/build/deps/readies/bin/getgcc

**Comment by baileyji** [comment]
My suspicion is still that the issue is simply that the docker environment reports a different uname that a direct system install and the script simply doesn't recognize the string. @chayim I was on a fully update Raspbian buster install using pip3 (as indeed pip defaults to py2) with python 3.7.3.

**Comment by chayim** [comment]
Could definitely be the uname, as it will return differently within a docker context versus system, and we parse it. @shan4usmani can I get your uname too? I can dummy something up in qemu to test.

**Comment by bijbis** [comment]
Getting the same error on RPi ...
Linux RevPi3208 4.19.95-rt38-v7 #1 SMP PREEMPT RT Tue, 22 Jun 2021 14:13:31 +0000 armv7l GNU/Linux

 make setup
Setting up system...
Traceback (most recent call last):
  File "./system-setup.py", line 56, in <module>
    RedisTimeSeriesSetup(nop = args.nop).setup()
  File "./system-setup.py", line 16, in __init__
    paella.Setup.__init__(self, nop)
  File "/home/pi/Downloads/RedisTimeSeries/deps/readies/paella/setup.py", line 337, in __init__
    self.package_manager = PackageManager.detect(self.platform, self.runner)
  File "/home/pi/Downloads/RedisTimeSeries/deps/readies/paella/setup.py", line 113, in detect
    raise self.Error("Cannot determine package manager for distibution %s" % platform.dist)
NameError: name 'self' is not defined
Makefile:23: recipe for target 'setup' failed
make: *** [setup] Error 1

**Comment by Abhishek010397** [comment]
i see ./system-setup.py it shows name self is not defined : 'NameError'

**Comment by Abhishek010397** [comment]
We solved this by using:-
Follow the below steps
1. git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries.git
2. cd RedisTimeSeries
3. ./deps/readies/bin/getpy3
4. make build & then check the bin folder in the RedisTimeSeries folder, it should get a redistimeseries.so
5. Then run the command as:- redis-server loadmodule bin/redistimeseries.so

**Comment by baileyji** [comment]
That is a variant of what I did as well to keep moving, note though that it is a workaround in that it doesn't solve the _issue_, which is that the recommended install procedure fails on Raspbian.

**Comment by shan4usmani** [comment]
"Cannot determine package manager for distibution %s" % platform.dist"

This is the original error that occurs in the RedisTimeSeries/deps/readies/paella/setup.py file. 

there are few platforms defined in the setup.py file, and according to the specific OS, the installer is determined ( i.e Dnf, Yum, Apt, etc). but Raspbian is not defined there. 

 @staticmethod
    def detect(platform, runner):
        if platform.os == 'linux':
            if platform.dist == 'fedora':  # also include centos 8
                return Dnf(runner)
            elif platform.is_debian_compat():
                return Apt(runner)
            elif platform.is_redhat_compat():
                return Yum(runner)
            elif platform.dist == 'suse':
                return Zypper(runner)
            elif platform.dist == 'arch':
                return Pacman(runner)
            elif platform.dist == 'alpine':
                return Alpine(runner)
            else:
                raise self.Error("Cannot determine package manager for distibution %s" % platform.dist)
        elif platform.os == 'macos':
            return Brew(runner)
        elif platform.os == 'freebsd':
            return Pkg(runner)
        else:
            raise Error("Cannot determine package manager for OS %s" % platform.os)


self.package_manager = PackageManager.detect(self.platform, self.runner) detects the package as "raspbian". so the above error is raised. 

you can add Raspbian and the installer as APT: 

elif platform.dist == 'raspbian'():
                return Apt(runner)


This is what worked for me.

**Comment by watfordjc** [comment]
I have created 3 patch files that appear to solve the issue for versions 1.4.7+ (unable to test building on 1.4.8+ because of #777).

The relevant patch should be applied to the ```readies``` submodule, i.e. ```git -C deps/readies apply ../../RedisTimeSeries-v1.4.10-master-readies-766b8a45074f3afdf8422dc239fa48b153e3af92.patch``` - don't forget to ```git submodule update --init --recursive``` first.

* [RedisTimeSeries-v1.4.7-v1.4.8-readies-96ba4bf1a18786ca02f5f3bb3d7a9a1124ab7fdd.patch.txt](https://github.com/RedisTimeSeries/RedisTimeSeries/files/7234729/RedisTimeSeries-v1.4.7-v1.4.8-readies-96ba4bf1a18786ca02f5f3bb3d7a9a1124ab7fdd.patch.txt) is for RedisTimeSeries versions 1.4.7 (the last to use ```python2```) and 1.4.8.
* [RedisTimeSeries-v1.4.9-readies-32e37e68f6ffa66f5a6e41cb37794147e84c38cb.patch.txt](https://github.com/RedisTimeSeries/RedisTimeSeries/files/7234730/RedisTimeSeries-v1.4.9-readies-32e37e68f6ffa66f5a6e41cb37794147e84c38cb.patch.txt) is for RedisTimeSeries version 1.4.9.
* [RedisTimeSeries-v1.4.10-master-readies-766b8a45074f3afdf8422dc239fa48b153e3af92.patch.txt](https://github.com/RedisTimeSeries/RedisTimeSeries/files/7234731/RedisTimeSeries-v1.4.10-master-readies-766b8a45074f3afdf8422dc239fa48b153e3af92.patch.txt) is for RedisTimeSeries version 1.4.10 to the current latest commit on master, a1b2db3. An issue should probably be opened in the upstream repository - this patch currently applies cleanly to the latest master branch commit (RedisLabsModules/readies@f6f7f79).

The patches have a ```.patch.txt``` extension because of GitHub attachment filename restrictions, and are [also available in a gist](https://gist.github.com/watfordjc/f3f21371a44e2e626c4fc52cfe36665d).

**Comment by chayim** [comment]
@watfordjc @baileyji @shan4usmani Would you all mind running ./deps/readies/bin/platform from the root of the recursively checked out redistimeseries repo?  Since I don't have the environment I need the exact outputs, and then can validate what we're doing accordingly.

Much obliged - then we'll get it in!

**Comment by watfordjc** [comment]
> Would you all mind running ./deps/readies/bin/platform from the root of the recursively checked out redistimeseries repo?

```
raspbian linux 10 (raspbian10) arm32v7
```

**Comment by chayim** [comment]
Thanks @watfordjc I added a PR based on the issue you raised in [readies](https://github.com/RedisLabsModules/readies/issues/63). Adding support for active versions of RedisTimeSeries will be done in this issue.

**Comment by danni-m** [comment]
@watfordjc is this issue still relevant?
